package com.t.zero.doc.words.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Documentinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.docId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private Integer docid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.name
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.originalName
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private String originalname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.uuid
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.userId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.state
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.createTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private LocalDateTime createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.updateTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private LocalDateTime updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.expireTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private LocalDateTime expiretime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentinfo.Remark
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table documentinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.docId
     *
     * @return the value of documentinfo.docId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public Integer getDocid() {
        return docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.docId
     *
     * @param docid the value for documentinfo.docId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setDocid(Integer docid) {
        this.docid = docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.name
     *
     * @return the value of documentinfo.name
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.name
     *
     * @param name the value for documentinfo.name
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.originalName
     *
     * @return the value of documentinfo.originalName
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public String getOriginalname() {
        return originalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.originalName
     *
     * @param originalname the value for documentinfo.originalName
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setOriginalname(String originalname) {
        this.originalname = originalname == null ? null : originalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.uuid
     *
     * @return the value of documentinfo.uuid
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.uuid
     *
     * @param uuid the value for documentinfo.uuid
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.userId
     *
     * @return the value of documentinfo.userId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.userId
     *
     * @param userid the value for documentinfo.userId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.state
     *
     * @return the value of documentinfo.state
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.state
     *
     * @param state the value for documentinfo.state
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.createTime
     *
     * @return the value of documentinfo.createTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public LocalDateTime getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.createTime
     *
     * @param createtime the value for documentinfo.createTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.updateTime
     *
     * @return the value of documentinfo.updateTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public LocalDateTime getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.updateTime
     *
     * @param updatetime the value for documentinfo.updateTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setUpdatetime(LocalDateTime updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.expireTime
     *
     * @return the value of documentinfo.expireTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public LocalDateTime getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.expireTime
     *
     * @param expiretime the value for documentinfo.expireTime
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setExpiretime(LocalDateTime expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentinfo.Remark
     *
     * @return the value of documentinfo.Remark
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentinfo.Remark
     *
     * @param remark the value for documentinfo.Remark
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", docid=").append(docid);
        sb.append(", name=").append(name);
        sb.append(", originalname=").append(originalname);
        sb.append(", uuid=").append(uuid);
        sb.append(", userid=").append(userid);
        sb.append(", state=").append(state);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", expiretime=").append(expiretime);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}