package com.t.zero.doc.words.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Logininfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.loginId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private Integer loginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.password
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.oldPassowd
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private String oldpassowd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.loginName
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.userId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.state
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.createDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private LocalDateTime createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.updateDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private LocalDateTime updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.expireDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private LocalDateTime expiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logininfo.remark
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.loginId
     *
     * @return the value of logininfo.loginId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public Integer getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.loginId
     *
     * @param loginid the value for logininfo.loginId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setLoginid(Integer loginid) {
        this.loginid = loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.password
     *
     * @return the value of logininfo.password
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.password
     *
     * @param password the value for logininfo.password
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.oldPassowd
     *
     * @return the value of logininfo.oldPassowd
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public String getOldpassowd() {
        return oldpassowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.oldPassowd
     *
     * @param oldpassowd the value for logininfo.oldPassowd
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setOldpassowd(String oldpassowd) {
        this.oldpassowd = oldpassowd == null ? null : oldpassowd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.loginName
     *
     * @return the value of logininfo.loginName
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.loginName
     *
     * @param loginname the value for logininfo.loginName
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.userId
     *
     * @return the value of logininfo.userId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.userId
     *
     * @param userid the value for logininfo.userId
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.state
     *
     * @return the value of logininfo.state
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.state
     *
     * @param state the value for logininfo.state
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.createDate
     *
     * @return the value of logininfo.createDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public LocalDateTime getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.createDate
     *
     * @param createdate the value for logininfo.createDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setCreatedate(LocalDateTime createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.updateDate
     *
     * @return the value of logininfo.updateDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public LocalDateTime getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.updateDate
     *
     * @param updatedate the value for logininfo.updateDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setUpdatedate(LocalDateTime updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.expireDate
     *
     * @return the value of logininfo.expireDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public LocalDateTime getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.expireDate
     *
     * @param expiredate the value for logininfo.expireDate
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setExpiredate(LocalDateTime expiredate) {
        this.expiredate = expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logininfo.remark
     *
     * @return the value of logininfo.remark
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logininfo.remark
     *
     * @param remark the value for logininfo.remark
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", loginid=").append(loginid);
        sb.append(", password=").append(password);
        sb.append(", oldpassowd=").append(oldpassowd);
        sb.append(", loginname=").append(loginname);
        sb.append(", userid=").append(userid);
        sb.append(", state=").append(state);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", expiredate=").append(expiredate);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}