package com.t.zero.doc.words.dao.auto;

import com.t.zero.doc.words.model.auto.Authinfo;
import com.t.zero.doc.words.model.auto.AuthinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    long countByExample(AuthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int deleteByExample(AuthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int deleteByPrimaryKey(Integer authid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int insert(Authinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int insertSelective(Authinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    List<Authinfo> selectByExample(AuthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    Authinfo selectByPrimaryKey(Integer authid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByExampleSelective(@Param("record") Authinfo record, @Param("example") AuthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByExample(@Param("record") Authinfo record, @Param("example") AuthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByPrimaryKeySelective(Authinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByPrimaryKey(Authinfo record);
}