package com.t.zero.doc.words.dao.auto;

import com.t.zero.doc.words.model.auto.Authrelation;
import com.t.zero.doc.words.model.auto.AuthrelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    long countByExample(AuthrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int deleteByExample(AuthrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int deleteByPrimaryKey(Integer authrelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int insert(Authrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int insertSelective(Authrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    List<Authrelation> selectByExample(AuthrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    Authrelation selectByPrimaryKey(Integer authrelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByExampleSelective(@Param("record") Authrelation record, @Param("example") AuthrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByExample(@Param("record") Authrelation record, @Param("example") AuthrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByPrimaryKeySelective(Authrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByPrimaryKey(Authrelation record);
}