package com.t.zero.doc.words.dao.auto;

import com.t.zero.doc.words.model.auto.Logininfo;
import com.t.zero.doc.words.model.auto.LogininfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogininfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    long countByExample(LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int deleteByExample(LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int deleteByPrimaryKey(Integer loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int insert(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int insertSelective(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    List<Logininfo> selectByExample(LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    Logininfo selectByPrimaryKey(Integer loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByExampleSelective(@Param("record") Logininfo record, @Param("example") LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByExample(@Param("record") Logininfo record, @Param("example") LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByPrimaryKeySelective(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Sun Jan 08 15:22:14 CST 2023
     */
    int updateByPrimaryKey(Logininfo record);
}