package com.t.zero.doc.words.dao.auto;

import com.t.zero.doc.words.model.auto.Rolerel;
import com.t.zero.doc.words.model.auto.RolerelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolerelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    long countByExample(RolerelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int deleteByExample(RolerelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int deleteByPrimaryKey(Integer rolerelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int insert(Rolerel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int insertSelective(Rolerel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    List<Rolerel> selectByExample(RolerelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    Rolerel selectByPrimaryKey(Integer rolerelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByExampleSelective(@Param("record") Rolerel record, @Param("example") RolerelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByExample(@Param("record") Rolerel record, @Param("example") RolerelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByPrimaryKeySelective(Rolerel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByPrimaryKey(Rolerel record);
}