package com.t.zero.doc.words.dao.auto;

import com.t.zero.doc.words.model.auto.Roleinfo;
import com.t.zero.doc.words.model.auto.RoleinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    long countByExample(RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int deleteByExample(RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int insert(Roleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int insertSelective(Roleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    List<Roleinfo> selectByExample(RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    Roleinfo selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByExampleSelective(@Param("record") Roleinfo record, @Param("example") RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByExample(@Param("record") Roleinfo record, @Param("example") RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByPrimaryKeySelective(Roleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByPrimaryKey(Roleinfo record);
}