package com.t.zero.doc.words.dao.auto;

import com.t.zero.doc.words.model.auto.Serviceinfo;
import com.t.zero.doc.words.model.auto.ServiceinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    long countByExample(ServiceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int deleteByExample(ServiceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int deleteByPrimaryKey(Integer serviceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int insert(Serviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int insertSelective(Serviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    List<Serviceinfo> selectByExample(ServiceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    Serviceinfo selectByPrimaryKey(Integer serviceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByExampleSelective(@Param("record") Serviceinfo record, @Param("example") ServiceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByExample(@Param("record") Serviceinfo record, @Param("example") ServiceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByPrimaryKeySelective(Serviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbg.generated Sun Jan 08 15:22:15 CST 2023
     */
    int updateByPrimaryKey(Serviceinfo record);
}